# Generated by Django 2.2.7 on 2019-12-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=512)),
                ('isbn', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('publishing_house', models.CharField(blank=True, db_index=True, max_length=50)),
                ('owner', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('descriptions', models.TextField(blank=True, db_index=True)),
            ],
        ),
    ]
