# Generated by Django 2.2.7 on 2019-12-27 14:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booksapp', '0003_auto_20191227_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliens',
            new_name='Clients',
        ),
    ]
