# Generated by Django 2.2.7 on 2019-12-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0004_auto_20191227_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
