# Generated by Django 2.2.7 on 2020-01-02 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0005_delete_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
