# Generated by Django 2.2.7 on 2020-01-03 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0008_auto_20200103_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
